//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pelicula()
        {
            this.Alquilers = new HashSet<Alquiler>();
        }
    
        public string PeliculaID { get; set; }
        public string Titulo { get; set; }
        public string Year { get; set; }
        public string Director { get; set; }
        public string Reparto { get; set; }
        public Nullable<int> RegistroNo { get; set; }
        public Nullable<int> CantidadEnExistencia { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string DistribuidoraID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alquiler> Alquilers { get; set; }
        public virtual Distribuidora Distribuidora { get; set; }
    }
}
